name = mtg_aliases_to_ccl
author = awuuwa
description = establishes compatibility between Minetest Game and CloneCraft;Libre
optional_depends = mcl_core, mcl_wool, mcl_raw_ores, mcl_trees, mcl_fences, mcl_flowers, mcl_beds, mcl_buckets, mcl_minecarts, mcl_farming, mcl_books, mcl_furnaces, mcl_tools, mcl_signs, mcl_stairs, mcl_mobitems, mcl_tnt, mcl_torches, mcl_nether, default, carts, flowers, doors, farming, fire, walls, wool, bones, beds, bucket, fireflies, stairs, tnt, xpanes, vessels
