name = mcl_beta_structures
author = mia
description = Retro-inspired beta/indev structures (brick pyramid, empty villages)
depends = mcl_init, mcl_core, mcl_trees, mcl_chests, mcl_doors, mcl_mobspawners, mcl_worlds, mcl_mapgen_core, mcl_structures, mobs_mc
