name = mcl_ccl_aliases
description = Compatibility with newer content from Mineclonia
depends = mcl_core, mobs_mc, mcl_fire, mcl_boats, mcl_mushrooms, mcl_bows, mcl_mobitems, mcl_tools, mcl_minecarts, mcl_farming, mcl_stairs, mcl_doors, mcl_sponges, mcl_nether, mcl_fences, mcl_trees, mcl_signs, mcl_torches, mcl_beds, mcl_fishing, mcl_wool, mcl_crafting_table, mcl_furnaces
optionaldepends = swamp, variety
