local modname = minetest.get_current_modname()
local S = minetest.get_translator(modname)

return {
	{S(""), 0xFFFFFF, {
		"“Free software” means software that respects users' freedom and community.",
		"",
		"",
		"It means that users have the freedom to",
		"run, copy, distribute, study,",
		"change and improve the software.",
		"Thus, “free software” is a matter of liberty,",
		"not price.",
		"",
		"",
		"",
		"",
		"",
		"To understand the concept,",
		"you should think of “free” as in “free speech,”",
		"not as in “free beer.”",
		"",
		"We sometimes call it “libre software,”",
		"borrowing the word from French or Spanish,",
		"",
		"",
		"",
		"",
		"",
		"You may or may not have paid money",
		"for a copy of a free program,",
		"",
		"",
		"Regardless of how you got your copies,",
		"with free software,",
		"you always have the freedom to",
		"copy and change the software,",
		"",
		"even to sell copies."
	}},
	{S("Free Software as defined by the four essential freedoms:"), 0xFFFFFF, {
		"\n\n0. to run the program,\n1. to study and change the program in source code form,\n2. to redistribute exact copies, and\n3. to distribute modified versions.\n",
	}},
	{S("betaclonia forked from Mineclonia and subsequently developed by"), 0xFF8040, {
		"awuuwa",
	}},
	{S("Creators of Mineclonia"), 0x0A9400, {
		"ryvnf",
		"cora",
	}},
	{S("Creator of MineClone 2"), 0xFFFFFF, {
		"Wuzzy",
	}},
	{S("Creator of MineClone"), 0xFF51D5, {
		"davedevils",
	}},
	{S("Mineclonia Contributors"), 0x52FF00, {
		"codiac",
		"DragonWrangler1",
		"JoseDouglas26",
		"Brama Udi",
		"amino",
		"Jürgen Rühle",
		"kno10",
		"Po Lu",
		"goblin_mode",
		"Lars Müller",
		"the-real-herowl",
		"nooneatall",
		"Lizzy Fleckenstein",
		"AFCMS",
		"NO11",
		"Brandon",
		"kay27",
		"marcin-serwin",
		"Michieal",
		"epCode",
		"PrairieWind",
		"chmodsayshello",
		"iliekprogrammar",
		"ancientmarinerdev",
		"TheOnlyJoeEnderman",
		"jordan4ibanez",
		"FossFanatic",
		"rubenwardy",
		"SumianVoice",
		"MysticTempest",
		"HimbeerserverDE",
		"MrRar",
		"kabou",
		"FaceDeer",
		"Nils Dagsson Moskopp",
		"ChrisPHP",
		"3raven",
		"ShadowRoi",
	}},
	{S("Original Mod Authors"), 0xA60014, {
		"Wuzzy",
		"Fleckenstein",
		"BlockMen",
		"TenPlus1",
		"PilzAdam",
		"ryvnf",
		"stujones11",
		"Arcelmi",
		"celeron55",
		"maikerumine",
		"GunshipPenguin",
		"Qwertymine3",
		"Rochambeau",
		"rubenwardy",
		"stu",
		"4aiman",
		"Kahrl",
		"Krock",
		"UgnilJoZ",
		"lordfingle",
		"22i",
		"bzoss",
		"kilbith",
		"xeranas",
		"kddekadenz",
		"sofar",
		"4Evergreen4",
		"jordan4ibanez",
		"paramat",
		"cora",
		"digitalnoob",
	}},
	{S("3D Models"), 0x343434, {
		"22i",
		"tobyplowy",
		"epCode",
		"pixelzone",
	}},
	{S("Textures and menu images"), 0x0019FF, {
		"XSSheep",
		"Wuzzy",
		"kingoscargames",
		"leorockway",
		"xMrVizzy",
		"yutyo",
		"NO11",
		"kay27",
		"MysticTempest",
		"RandomLegoBrick",
		"cora",
		"Michieal",
		"ryvnf",
		"SmokeyDope",
		"Aeonix_Aeon",
		"Nicu",
		"Exhale",
		"Aeonix_Aeon",
		"Wbjitscool",
		"SmokeyDope",
		"pixelzone",
	}},
	{S("Translations"), 0xFF9705, {
		"Wuzzy",
		"Rocher Laurent",
		"wuniversales",
		"kay27",
		"pitchum",
		"todoporlalibertad",
		"Marcin Serwin",
		"Pepebotella",
		"Emojigit",
		"snowyu",
		"3raven",
		"Riu Sakura",
		"3raven",
		"Ame-chan-angel",
		"Application-Maker",
		"Benny",
		"collectanos",
		"Cwpute",
		"Dirk",
		"Enlive",
		"fnetX",
		"Gaemy",
		"hugoalh",
		"j-r",
		"Kyoushi",
		"liulitchi",
		"mugcake",
		"phileas",
		"Pietro Cappuccino",
		"RadonPrunus",
		"Sencyy",
		"Sotis",
		"Zozosticot",
	}},
	{S("Special thanks"), 0x00FF60, {
		"celeron55 for creating Luanti (Minetest)",
		"Jordach for the jukebox music compilation from Big Freaking Dig",
		"The workaholics who spent way too much time writing for one Minecraft Wiki.",
		"Notch and Jeb as the major forces behind the game that inspired the Free/Libre clone games",
	}},
	{S("Say no to non-free software"), 0xFFFFFF, {
		"say no to surveillance",
		"say no to DRM",
	}},
}
