name = mcl_bows
author = Arcelmi
description = This mod adds bows and arrows for MineClone 2.
depends = controls, mcl_init, mcl_util
optional_depends = mcl_core, mcl_mobitems, playerphysics, doc, doc_identifier, mesecons_button

