name = mcl_armor
author = stu
description = Adds craftable armor that is visible to other players.
depends = mcl_init, mcl_core, mcl_player, mcl_damage, mcl_colors, mcl_dyes, mcl_fire
optional_depends = mcl_fire, ethereal, bakedclay
