name = mobs_mc
author = maikerumine
description = Adds The OG Game-like monsters and animals.
depends = mcl_init, mcl_mobs, mcl_wip, mcl_core, mcl_util, mcl_moon, mcl_worlds, mcl_dyes, mcl_entity_invs
optional_depends = mcl_jukebox
